from __future__ import annotations

from hashlib import sha256
from importlib import metadata as importlib_metadata
import json
from pathlib import Path
from typing import Any

from core.paths import PATHS
from engines.manager import EngineManager


_PACKAGE_NAMES = {
    "kokoro": "kokoro",
    "piper": "piper-tts",
    "xtts": "TTS",
}


def _package_version(package_name: str) -> str:
    try:
        return importlib_metadata.version(package_name)
    except importlib_metadata.PackageNotFoundError:
        return "not-installed"
    except Exception:
        return "unknown"


def engine_fingerprint(engine_name: str) -> dict[str, Any]:
    """Return a stable engine signature used by crash-safe chunk reuse.

    The signature intentionally avoids loading a model. It changes when the
    selected package, engine module, or manifest changes, which prevents audio
    generated by an older implementation from being silently reused.
    """

    engine_id = str(engine_name or "kokoro").strip().lower()
    package_name = _PACKAGE_NAMES.get(engine_id, engine_id)
    version = _package_version(package_name)

    manager = EngineManager()
    try:
        manifest = manager.manifest(engine_id)
        manifest_data = manifest.to_dict()
        module_name = manifest.module
    except Exception:
        manifest_data = {"id": engine_id}
        module_name = f"engines.{engine_id}"

    module_path = PATHS.project_root / Path(*module_name.split(".")).with_suffix(".py")
    module_hash = "missing"
    if module_path.is_file():
        try:
            module_hash = sha256(module_path.read_bytes()).hexdigest()
        except OSError:
            module_hash = "unreadable"

    manifest_source = manifest_data.pop("source", None)
    manifest_hash = "builtin"
    if manifest_source:
        source_path = Path(str(manifest_source))
        if source_path.is_file():
            try:
                manifest_hash = sha256(source_path.read_bytes()).hexdigest()
            except OSError:
                manifest_hash = "unreadable"
    else:
        encoded = json.dumps(manifest_data, sort_keys=True, ensure_ascii=False).encode("utf-8")
        manifest_hash = sha256(encoded).hexdigest()

    return {
        "engine": engine_id,
        "package": package_name,
        "package_version": version,
        "module_hash": module_hash,
        "manifest_hash": manifest_hash,
    }
